//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 04:24:17 PM IST 
//


package com.nokia.cm.converter.parameter.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nokia.cm.converter.parameter.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nokia.cm.converter.parameter.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductData }
     * 
     */
    public ProductData createProductData() {
        return new ProductData();
    }

    /**
     * Create an instance of {@link Interfaces }
     * 
     */
    public Interfaces createInterfaces() {
        return new Interfaces();
    }

    /**
     * Create an instance of {@link SimpleType }
     * 
     */
    public SimpleType createSimpleType() {
        return new SimpleType();
    }

    /**
     * Create an instance of {@link SimpleType.Editing }
     * 
     */
    public SimpleType.Editing createSimpleTypeEditing() {
        return new SimpleType.Editing();
    }

    /**
     * Create an instance of {@link Pdmeta }
     * 
     */
    public Pdmeta createPdmeta() {
        return new Pdmeta();
    }

    /**
     * Create an instance of {@link ManagedObject }
     * 
     */
    public ManagedObject createManagedObject() {
        return new ManagedObject();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link ShortDesc }
     * 
     */
    public ShortDesc createShortDesc() {
        return new ShortDesc();
    }

    /**
     * Create an instance of {@link Creation }
     * 
     */
    public Creation createCreation() {
        return new Creation();
    }

    /**
     * Create an instance of {@link Modification }
     * 
     */
    public Modification createModification() {
        return new Modification();
    }

    /**
     * Create an instance of {@link ProductData.Property }
     * 
     */
    public ProductData.Property createProductDataProperty() {
        return new ProductData.Property();
    }

    /**
     * Create an instance of {@link Interfaces.Interface }
     * 
     */
    public Interfaces.Interface createInterfacesInterface() {
        return new Interfaces.Interface();
    }

    /**
     * Create an instance of {@link SimpleType.Editing.Range }
     * 
     */
    public SimpleType.Editing.Range createSimpleTypeEditingRange() {
        return new SimpleType.Editing.Range();
    }

}
