//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 04:24:17 PM IST 
//


package com.nokia.cm.converter.parameter.dto;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simpleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="editing"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="range"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="minIncl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="maxIncl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="base" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simpleType", propOrder = {
    "editing"
})
public class SimpleType {

    @XmlElement(required = true)
    protected SimpleType.Editing editing;
    @XmlAttribute(name = "base")
    protected String base;

    /**
     * Gets the value of the editing property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleType.Editing }
     *     
     */
    public SimpleType.Editing getEditing() {
        return editing;
    }

    /**
     * Sets the value of the editing property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleType.Editing }
     *     
     */
    public void setEditing(SimpleType.Editing value) {
        this.editing = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="range"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="minIncl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="maxIncl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "range"
    })
    public static class Editing {

        @XmlElement(required = true)
        protected SimpleType.Editing.Range range;

        /**
         * Gets the value of the range property.
         * 
         * @return
         *     possible object is
         *     {@link SimpleType.Editing.Range }
         *     
         */
        public SimpleType.Editing.Range getRange() {
            return range;
        }

        /**
         * Sets the value of the range property.
         * 
         * @param value
         *     allowed object is
         *     {@link SimpleType.Editing.Range }
         *     
         */
        public void setRange(SimpleType.Editing.Range value) {
            this.range = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="minIncl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="maxIncl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Range {

            @XmlAttribute(name = "minIncl")
            protected Integer minIncl;
            @XmlAttribute(name = "maxIncl")
            protected Integer maxIncl;
            @XmlAttribute(name = "step")
            protected BigDecimal step;

            /**
             * Gets the value of the minIncl property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getMinIncl() {
                return minIncl;
            }

            /**
             * Sets the value of the minIncl property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMinIncl(Integer value) {
                this.minIncl = value;
            }

            /**
             * Gets the value of the maxIncl property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getMaxIncl() {
                return maxIncl;
            }

            /**
             * Sets the value of the maxIncl property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMaxIncl(Integer value) {
                this.maxIncl = value;
            }

            /**
             * Gets the value of the step property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getStep() {
                return step;
            }

            /**
             * Sets the value of the step property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setStep(BigDecimal value) {
                this.step = value;
            }

        }

    }

}
