//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 03:59:12 PM IST 
//


package com.base.topology.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DomainAbbrName"/>
 *         &lt;element ref="{}ProductAbbrName"/>
 *         &lt;element ref="{}MOClass"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domainAbbrName",
    "productAbbrName",
    "moClass"
})
@XmlRootElement(name = "MOClassList")
public class MOClassList {

    @XmlElement(name = "DomainAbbrName", required = true)
    protected String domainAbbrName;
    @XmlElement(name = "ProductAbbrName", required = true)
    protected String productAbbrName;
    @XmlElement(name = "MOClass", required = true)
    protected MOClass moClass;

    /**
     * Gets the value of the domainAbbrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainAbbrName() {
        return domainAbbrName;
    }

    /**
     * Sets the value of the domainAbbrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainAbbrName(String value) {
        this.domainAbbrName = value;
    }

    /**
     * Gets the value of the productAbbrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductAbbrName() {
        return productAbbrName;
    }

    /**
     * Sets the value of the productAbbrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductAbbrName(String value) {
        this.productAbbrName = value;
    }

    /**
     * Gets the value of the moClass property.
     * 
     * @return
     *     possible object is
     *     {@link MOClass }
     *     
     */
    public MOClass getMOClass() {
        return moClass;
    }

    /**
     * Sets the value of the moClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MOClass }
     *     
     */
    public void setMOClass(MOClass value) {
        this.moClass = value;
    }

}
