//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 03:59:12 PM IST 
//


package com.base.topology.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.base.topology.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _AbbrName_QNAME = new QName("", "AbbrName");
    private final static QName _DomainAbbrName_QNAME = new QName("", "DomainAbbrName");
    private final static QName _Update_QNAME = new QName("", "Update");
    private final static QName _Create_QNAME = new QName("", "Create");
    private final static QName _Delete_QNAME = new QName("", "Delete");
    private final static QName _ProductAbbrName_QNAME = new QName("", "ProductAbbrName");
    private final static QName _MaxInstances_QNAME = new QName("", "MaxInstances");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.base.topology.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MOClassList }
     * 
     */
    public MOClassList createMOClassList() {
        return new MOClassList();
    }

    /**
     * Create an instance of {@link MOClass }
     * 
     */
    public MOClass createMOClass() {
        return new MOClass();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AbbrName")
    public JAXBElement<String> createAbbrName(String value) {
        return new JAXBElement<String>(_AbbrName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DomainAbbrName")
    public JAXBElement<String> createDomainAbbrName(String value) {
        return new JAXBElement<String>(_DomainAbbrName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Update")
    public JAXBElement<String> createUpdate(String value) {
        return new JAXBElement<String>(_Update_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Create")
    public JAXBElement<String> createCreate(String value) {
        return new JAXBElement<String>(_Create_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Delete")
    public JAXBElement<String> createDelete(String value) {
        return new JAXBElement<String>(_Delete_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProductAbbrName")
    public JAXBElement<String> createProductAbbrName(String value) {
        return new JAXBElement<String>(_ProductAbbrName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaxInstances")
    public JAXBElement<Byte> createMaxInstances(Byte value) {
        return new JAXBElement<Byte>(_MaxInstances_QNAME, Byte.class, null, value);
    }

}
